### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by ghost** [relativemodder/account_statuses#4]
you can easily go to https://gdstatus.7m.pl/updateStatus.php?accountID=1&status=dnd to change a status 

maybe in the server code, add a check where it will send a request to robtops servers to login to the account and verify its a valid account owner

**Comment by relativemodder** [comment]
I'm too lazy and I quit geode modding for some reasons I don't want to tell

**Comment by ghost** [comment]
> I'm too lazy and I quit geode modding for some reasons I don't want to tell

ok

**Comment by ghost** [comment]
you are fine dw, im just pointing it out
